### ISSUE TITLE
Velocloud event logs is not shown in Modular Data Inputs

### ISSUE THREAD

**Issue by Subachinraj** [djsincla/TA_VeloCloud#2]
I am using splunk version Version: 8.1.6

I have copied the folder "TA_Velocloud" to splunk/apps and restarted splunk. But Velocloud Modular input was not appearing in the data inputs

**Comment by djsincla** [comment]
Thanks,

1. There are three versions - Which version did you download and install? With current versions of Splunk, you would be best advised to use the Python3 or Token3 version.

2.  Can you provide a screenshot of the directory with the plugin. As an example: 



Regards Dwayne

**Comment by Subachinraj** [comment]
VeloCloud Event Log
Version:1.0.10 Build:110

Splunk Python version is 3.7.10

Kindly share the steps and link to download the supported velocloud version

![image](https://user-images.githubusercontent.com/96241254/146422546-5b617d7d-c155-4af9-b515-44f8d6d38630.png)

**Comment by djsincla** [comment]
Thanks! Install looks good, but you will need one of the other versions:

From GitHub, select the Token3 or Python3 branch:



Python3 branch is similar to the master branch except based on Python V3 and uses a userid and password. 
 
Token3 branch is also Python 3 based but uses an API token created in VCO to authenticate.

Regards Dwayne

**Comment by Subachinraj** [comment]
HI Dwayne,

I have downloaded python3 version and have provided the url, username and password for Velocloud in Modular inputs. Account is an standard admin account. But i couldnt able to see logs in splunk. Not sure what i am missing. Is there any prerequisite to be done from Velocloud end.
